# Use the same environment regardless of whether we use 
# `su <package>' or 'su - <package>' to become the package user.
source ~/.bash_profile
# Personal aliases and functions.
# Fun as it was, hello caused a problem with the automake "make check"
#hello (){
#   echo "Hello yourself $(whoami) :)";
#}
# make available to scripts
#export -f hello;
