#!/bin/bash
# Copyright (c) 2000,2004 Matthias S. Benkmann <article AT winterdrache DOT de>
# You may do everything with this code except misrepresent its origin.
# PROVIDED `AS IS' WITH ABSOLUTELY NO WARRANTY OF ANY KIND!
# 
# Altered by Robert Taylor <rtaylor777 AT gmail DOT com> April 2013
DAISY_CHAIN="";

for p in $(type -ap chgrp) ; do
  if [ ! $p -ef $0 ]; then DAISY_CHAIN="$p" ; break ; fi
done

if [ -z "$DAISY_CHAIN" ]; then
  echo "Cannot find real ${0##*/} command";
  exit 1;
fi

echo 1>&2 '***' chgrp "$@";

if [ $UID -eq 0 ]; then
  exec $DAISY_CHAIN "$@";
fi

exit 0;
