#!/bin/bash
# Copyright (c) 2000,2004 Matthias S. Benkmann <article AT winterdrache DOT de>
# You may do everything with this code except misrepresent its origin.
# PROVIDED `AS IS' WITH ABSOLUTELY NO WARRANTY OF ANY KIND!
# 
# Altered by Robert Taylor <rtaylor777 AT gmail DOT com> April 2013
DAISY_CHAIN="";
reportmsg="chown";
for item in "$@"; do
    regex="^.*['[:space:]].*$";
    if [[ "$item" =~ $regex ]]; then
        regex="^(.*=)(.*['[:space:]].*)$";
        if [[ "$item" =~ $regex ]]; then
            reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
        else
            reportmsg="$reportmsg \"$item\"";
        fi
    else
        reportmsg="$reportmsg $item";
    fi
done

for p in $(type -ap chown) ; do
  if [ ! $p -ef $0 ]; then DAISY_CHAIN="$p" ; break ; fi
done

if [ -z "$DAISY_CHAIN" ]; then
  echo "Cannot find real ${0##*/} command";
  exit 1;
fi

error_code=0;
if [[ $UID -eq 0 ]]; then
  $DAISY_CHAIN "$@" || error_code="$?";
  exit $error_code; #pass back any error code
fi

if [[ "$DISABLE_WRAPPERS" -eq 1 ]]; then
  $DAISY_CHAIN "$@" || error_code="$?";
  exit $error_code; #pass back any error code
fi

pwd=$(pwd);

chown_audit_log(){  
    echo 1>&2 "*** Prevented the \"$reportmsg\" command from executing.";
    echo 1>&2 "*** See the $HOME/chown_audit.txt file for details";
    text="\n";
    text="$text ------ original command -------------\n";
    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
    text="$text The execution of this command was prevented. Run as root if desired.\n";
    printf "$text" >>"$HOME/chown_audit.txt";
}

chown_audit_log;

exit 0;
